// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlilsrclvzqjxbytntrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsaWxzcmNsdnpxanhieXRudHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3ODk4MzcsImV4cCI6MjA1NzM2NTgzN30.rHEtzUaw5kOmX7VdffqYqk0CQjq3jf_ILLQvvIIMF8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);